"""Add DatasetRow only

Revision ID: 28fa6a6c63d0
Revises: 
Create Date: 2025-06-25 15:28:30.776455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28fa6a6c63d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('dataset_rows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('row_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('key', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('value', sa.Text(), nullable=True))
        batch_op.alter_column('upload_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_index('ix_datasetrow_hospital_key', ['hospital_id', 'key'], unique=False)
        batch_op.drop_constraint(batch_op.f('dataset_rows_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Uploads', ['upload_id'], ['upload_id'])
        batch_op.drop_column('row_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_rows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_data', mysql.JSON(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('dataset_rows_ibfk_1'), 'uploads', ['upload_id'], ['upload_id'])
        batch_op.drop_index('ix_datasetrow_hospital_key')
        batch_op.alter_column('upload_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('value')
        batch_op.drop_column('key')
        batch_op.drop_column('row_index')
        batch_op.drop_column('hospital_id')
